version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - /Users/coutinhonobre/Projects/computer_vision:/home/jovyan/work
